name: spm_ml
channels:
  - defaults
  - pytorch
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - filelock=3.20.3
  - gmp=6.3.0
  - gmpy2=2.2.2
  - jinja2=3.1.6
  - libcxx=21.1.8
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libopenblas=0.3.31
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=26.0.1
  - python=3.10.19
  - pytorch=2.5.1
  - pyyaml=6.0.3
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - sympy=1.14.0
  - tk=8.6.15
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wheel=0.46.3
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - pip:
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - h5py==3.15.1
      - humanfriendly==10.0
      - kiwisolver==1.4.9
      - lmdb==1.7.5
      - matplotlib==3.10.8
      - ml-dtypes==0.5.4
      - onnx==1.20.1
      - onnxruntime==1.23.2  # 注意：pip 最新版本，CMake 构建使用 1.24.2
      - PyQt5==5.15.11  # Windows 图形界面
      - pillow==12.1.1
      - protobuf==6.33.5
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - six==1.17.0
      - tqdm==4.67.3
prefix: /Users/zhangjinlin/miniconda3/envs/spm_ml
